FROM node:20-alpine AS node-base

WORKDIR /blockchain

COPY package.json ./
RUN npm install

COPY . .

FROM ghcr.io/foundry-rs/foundry:latest

WORKDIR /blockchain

COPY --from=node-base /usr/local/bin/node /usr/local/bin/
COPY --from=node-base /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

COPY --from=node-base /blockchain /blockchain

RUN chmod +x /blockchain/scripts/setup.sh

CMD ["tail", "-f", "/dev/null"]
